const express = require('express');
const mongoose = require('mongoose');
const file = require('fs');
const userRouter = require('./routes/user');
const assetRouter = require('./routes/asset');
const trackingRouter = require('./routes/tracking');
const bodyParser = require('body-parser');
require('dotenv').config();
mongoose.set('strictQuery', true);
const app = express();
app.use(bodyParser.json());
mongoose.connect('mongodb://localhost/company');
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use('/user', userRouter);
app.use('/asset', assetRouter);
app.use('/tracking', trackingRouter);
const PORT = process.env.PORT || 2000;
app.listen(PORT);
console.log('server is running on PORT', PORT);
