const express = require('express');
const mongoose = require('mongoose');
// const jwt = require('jsonwebtoken');
const userRouter = require('./routes/user');
const assetRouter = require('./routes/asset');
const trackingRouter = require('./routes/tracking');
const bodyParser = require('body-parser');
require('dotenv').config();
mongoose.set('strictQuery', true);
const app = express();
app.use(bodyParser.json());
mongoose.connect('mongodb://localhost/company');
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use('/user', userRouter);
app.use('/asset', assetRouter);
app.use('/tracking', trackingRouter);
// const port = process.env.PORT || 2000;
// console.log('port no is ', port);
app.listen(2000);
